[project]
name = "wids-2025-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "pip>=25.0.1",
    "certifi>=2025.1.31",
    "python-certifi-win32>=1.6.1",
    "xlsxwriter>=3.2.2",
    "jupyter>=1.1.1",
    "pytest>=8.3.5",
    "truststore>=0.10.1",
    "openpyxl",
    "matplotlib>=3.10.1",
    "sweetviz",
    "pandas",
    "numpy<2.0.0",
    "kaggle",
    "scikit-learn",
    "lightgbm",
    "xgboost",
    "catboost",
    "umap-learn",
    "numpy",
    "seaborn",
]
